create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_gt_init_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 29 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {the_clock_unit/clk_ram_freq[0]} {the_clock_unit/clk_ram_freq[1]} {the_clock_unit/clk_ram_freq[2]} {the_clock_unit/clk_ram_freq[3]} {the_clock_unit/clk_ram_freq[4]} {the_clock_unit/clk_ram_freq[5]} {the_clock_unit/clk_ram_freq[6]} {the_clock_unit/clk_ram_freq[7]} {the_clock_unit/clk_ram_freq[8]} {the_clock_unit/clk_ram_freq[9]} {the_clock_unit/clk_ram_freq[10]} {the_clock_unit/clk_ram_freq[11]} {the_clock_unit/clk_ram_freq[12]} {the_clock_unit/clk_ram_freq[13]} {the_clock_unit/clk_ram_freq[14]} {the_clock_unit/clk_ram_freq[15]} {the_clock_unit/clk_ram_freq[16]} {the_clock_unit/clk_ram_freq[17]} {the_clock_unit/clk_ram_freq[18]} {the_clock_unit/clk_ram_freq[19]} {the_clock_unit/clk_ram_freq[20]} {the_clock_unit/clk_ram_freq[21]} {the_clock_unit/clk_ram_freq[22]} {the_clock_unit/clk_ram_freq[23]} {the_clock_unit/clk_ram_freq[24]} {the_clock_unit/clk_ram_freq[25]} {the_clock_unit/clk_ram_freq[26]} {the_clock_unit/clk_ram_freq[27]} {the_clock_unit/clk_ram_freq[28]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 29 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {the_clock_unit/clk_sys_freq[0]} {the_clock_unit/clk_sys_freq[1]} {the_clock_unit/clk_sys_freq[2]} {the_clock_unit/clk_sys_freq[3]} {the_clock_unit/clk_sys_freq[4]} {the_clock_unit/clk_sys_freq[5]} {the_clock_unit/clk_sys_freq[6]} {the_clock_unit/clk_sys_freq[7]} {the_clock_unit/clk_sys_freq[8]} {the_clock_unit/clk_sys_freq[9]} {the_clock_unit/clk_sys_freq[10]} {the_clock_unit/clk_sys_freq[11]} {the_clock_unit/clk_sys_freq[12]} {the_clock_unit/clk_sys_freq[13]} {the_clock_unit/clk_sys_freq[14]} {the_clock_unit/clk_sys_freq[15]} {the_clock_unit/clk_sys_freq[16]} {the_clock_unit/clk_sys_freq[17]} {the_clock_unit/clk_sys_freq[18]} {the_clock_unit/clk_sys_freq[19]} {the_clock_unit/clk_sys_freq[20]} {the_clock_unit/clk_sys_freq[21]} {the_clock_unit/clk_sys_freq[22]} {the_clock_unit/clk_sys_freq[23]} {the_clock_unit/clk_sys_freq[24]} {the_clock_unit/clk_sys_freq[25]} {the_clock_unit/clk_sys_freq[26]} {the_clock_unit/clk_sys_freq[27]} {the_clock_unit/clk_sys_freq[28]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 29 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {the_clock_unit/clk_gt_ref_freq[0]} {the_clock_unit/clk_gt_ref_freq[1]} {the_clock_unit/clk_gt_ref_freq[2]} {the_clock_unit/clk_gt_ref_freq[3]} {the_clock_unit/clk_gt_ref_freq[4]} {the_clock_unit/clk_gt_ref_freq[5]} {the_clock_unit/clk_gt_ref_freq[6]} {the_clock_unit/clk_gt_ref_freq[7]} {the_clock_unit/clk_gt_ref_freq[8]} {the_clock_unit/clk_gt_ref_freq[9]} {the_clock_unit/clk_gt_ref_freq[10]} {the_clock_unit/clk_gt_ref_freq[11]} {the_clock_unit/clk_gt_ref_freq[12]} {the_clock_unit/clk_gt_ref_freq[13]} {the_clock_unit/clk_gt_ref_freq[14]} {the_clock_unit/clk_gt_ref_freq[15]} {the_clock_unit/clk_gt_ref_freq[16]} {the_clock_unit/clk_gt_ref_freq[17]} {the_clock_unit/clk_gt_ref_freq[18]} {the_clock_unit/clk_gt_ref_freq[19]} {the_clock_unit/clk_gt_ref_freq[20]} {the_clock_unit/clk_gt_ref_freq[21]} {the_clock_unit/clk_gt_ref_freq[22]} {the_clock_unit/clk_gt_ref_freq[23]} {the_clock_unit/clk_gt_ref_freq[24]} {the_clock_unit/clk_gt_ref_freq[25]} {the_clock_unit/clk_gt_ref_freq[26]} {the_clock_unit/clk_gt_ref_freq[27]} {the_clock_unit/clk_gt_ref_freq[28]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_gt_init_BUFG]
