# SPDX-License-Identifier: BSD-2-Clause-Views
# Copyright (c) 2019-2023 The Regents of the University of California


# FPGA settings
FPGA_PART = xc7k355tffg901-1
FPGA_TOP = aurora_tx_fifo


# Files for synthesis
SYN_FILES  = ../../../src/rtl/aurora/aurora_tx_fifo.sv


# File for simulation
SIM_FILES = ../aurora_tx_fifo_tb.sv


# XDC files
# XDC_FILES =


# IP
# IP_TCL_FILES =


# Configuration
# CONFIG_TCL_FILES = ./config.tcl


include ../../../../common/vivado.mk
