# Configuration voltages
set_property CFGBVS         VCCO                [current_design]
set_property CONFIG_VOLTAGE 3.3                 [current_design]
#
# System clock
set_property IOSTANDARD     DIFF_SSTL15         [get_ports {clk_100mhz_?}]
set_property PACKAGE_PIN    AG10                [get_ports {clk_100mhz_p}]
set_property PACKAGE_PIN    AH10                [get_ports {clk_100mhz_n}]
#
# DDR3 Reset
set_property SLEW           FAST                [get_ports {ddr3_reset_n}]
set_property IOSTANDARD     LVCMOS15            [get_ports {ddr3_reset_n}]
set_property PACKAGE_PIN    AH4                 [get_ports {ddr3_reset_n}]
#
# DDR3 Clock
set_property SLEW           FAST                [get_ports {ddr3_ck_?[0]}]
set_property IOSTANDARD     DIFF_SSTL15         [get_ports {ddr3_ck_?[0]}]
set_property PACKAGE_PIN    AD2                 [get_ports {ddr3_ck_p[0]}]
set_property PACKAGE_PIN    AD1                 [get_ports {ddr3_ck_n[0]}]
#
# DDR3 Control
set_property SLEW           FAST                [get_ports {ddr3_addr[*]}]
set_property IOSTANDARD     SSTL15              [get_ports {ddr3_addr[*]}]
set_property PACKAGE_PIN    AG4                 [get_ports {ddr3_addr[0]}]
set_property PACKAGE_PIN    AF1                 [get_ports {ddr3_addr[1]}]
set_property PACKAGE_PIN    AE1                 [get_ports {ddr3_addr[2]}]
set_property PACKAGE_PIN    AF2                 [get_ports {ddr3_addr[3]}]
set_property PACKAGE_PIN    AF3                 [get_ports {ddr3_addr[4]}]
set_property PACKAGE_PIN    AC7                 [get_ports {ddr3_addr[5]}]
set_property PACKAGE_PIN    AE6                 [get_ports {ddr3_addr[6]}]
set_property PACKAGE_PIN    AD6                 [get_ports {ddr3_addr[7]}]
set_property PACKAGE_PIN    AC4                 [get_ports {ddr3_addr[8]}]
set_property PACKAGE_PIN    AC5                 [get_ports {ddr3_addr[9]}]
set_property PACKAGE_PIN    AC1                 [get_ports {ddr3_addr[10]}]
set_property PACKAGE_PIN    AC2                 [get_ports {ddr3_addr[11]}]
set_property PACKAGE_PIN    AD3                 [get_ports {ddr3_addr[12]}]
set_property PACKAGE_PIN    AD4                 [get_ports {ddr3_addr[13]}]
#
set_property SLEW           FAST                [get_ports {ddr3_ba[*]}]
set_property IOSTANDARD     SSTL15              [get_ports {ddr3_ba[*]}]
set_property PACKAGE_PIN    AE3                 [get_ports {ddr3_ba[0]}]
set_property PACKAGE_PIN    AE4                 [get_ports {ddr3_ba[1]}]
set_property PACKAGE_PIN    AG3                 [get_ports {ddr3_ba[2]}]
#
set_property SLEW           FAST                [get_ports {ddr3_cas_n}]
set_property IOSTANDARD     SSTL15              [get_ports {ddr3_cas_n}]
set_property PACKAGE_PIN    AF5                 [get_ports {ddr3_cas_n}]
#
set_property SLEW           FAST                [get_ports {ddr3_cke[0]}]
set_property IOSTANDARD     SSTL15              [get_ports {ddr3_cke[0]}]
set_property PACKAGE_PIN    AG2                 [get_ports {ddr3_cke[0]}]
#
set_property SLEW           FAST                [get_ports {ddr3_cs_n[0]}]
set_property IOSTANDARD     SSTL15              [get_ports {ddr3_cs_n[0]}]
set_property PACKAGE_PIN    AG5                 [get_ports {ddr3_cs_n[0]}]
#
set_property SLEW           FAST                [get_ports {ddr3_odt[0]}]
set_property IOSTANDARD     SSTL15              [get_ports {ddr3_odt[0]}]
set_property PACKAGE_PIN    AH1                 [get_ports {ddr3_odt[0]}]
#
set_property SLEW           FAST                [get_ports {ddr3_ras_n}]
set_property IOSTANDARD     SSTL15              [get_ports {ddr3_ras_n}]
set_property PACKAGE_PIN    AE5                 [get_ports {ddr3_ras_n}]
#
set_property SLEW           FAST                [get_ports {ddr3_we_n}]
set_property IOSTANDARD     SSTL15              [get_ports {ddr3_we_n}]
set_property PACKAGE_PIN    AF6                 [get_ports {ddr3_we_n}]
#
# DDR3 DQ
set_property SLEW           FAST                [get_ports {ddr3_dq[*]}]
set_property IOSTANDARD     SSTL15_T_DCI        [get_ports {ddr3_dq[*]}]
set_property PACKAGE_PIN    AF7                 [get_ports {ddr3_dq[0]}]
set_property PACKAGE_PIN    AG7                 [get_ports {ddr3_dq[1]}]
set_property PACKAGE_PIN    AJ6                 [get_ports {ddr3_dq[2]}]
set_property PACKAGE_PIN    AK6                 [get_ports {ddr3_dq[3]}]
set_property PACKAGE_PIN    AJ8                 [get_ports {ddr3_dq[4]}]
set_property PACKAGE_PIN    AK8                 [get_ports {ddr3_dq[5]}]
set_property PACKAGE_PIN    AK5                 [get_ports {ddr3_dq[6]}]
set_property PACKAGE_PIN    AK4                 [get_ports {ddr3_dq[7]}]
set_property PACKAGE_PIN    AB12                [get_ports {ddr3_dq[8]}]
set_property PACKAGE_PIN    AA8                 [get_ports {ddr3_dq[9]}]
set_property PACKAGE_PIN    AB8                 [get_ports {ddr3_dq[10]}]
set_property PACKAGE_PIN    Y11                 [get_ports {ddr3_dq[11]}]
set_property PACKAGE_PIN    Y10                 [get_ports {ddr3_dq[12]}]
set_property PACKAGE_PIN    AA11                [get_ports {ddr3_dq[13]}]
set_property PACKAGE_PIN    AA10                [get_ports {ddr3_dq[14]}]
set_property PACKAGE_PIN    AA13                [get_ports {ddr3_dq[15]}]
#
# DDR3 DQS
set_property SLEW           FAST                [get_ports {ddr3_dqs_?[*]}]
set_property IOSTANDARD     DIFF_SSTL15_T_DCI   [get_ports {ddr3_dqs_?[*]}]
set_property PACKAGE_PIN    AH7                 [get_ports {ddr3_dqs_p[0]}]
set_property PACKAGE_PIN    AJ7                 [get_ports {ddr3_dqs_n[0]}]
set_property PACKAGE_PIN    AB9                 [get_ports {ddr3_dqs_p[1]}]
set_property PACKAGE_PIN    AC9                 [get_ports {ddr3_dqs_n[1]}]
#
# DDR3 DM
set_property SLEW           FAST                [get_ports {ddr3_dm[*]}]
set_property IOSTANDARD     SSTL15              [get_ports {ddr3_dm[*]}]
set_property PACKAGE_PIN    AF8                 [get_ports {ddr3_dm[0]}]
set_property PACKAGE_PIN    AA12                [get_ports {ddr3_dm[1]}]
#
# QSPI Flash
set_property IOSTANDARD     LVCMOS33            [get_ports {flash_*}]
set_property PACKAGE_PIN    U19                 [get_ports {flash_cs_n}]
set_property PACKAGE_PIN    P24                 [get_ports {flash_data[0]}]
set_property PACKAGE_PIN    R25                 [get_ports {flash_data[1]}]
set_property PACKAGE_PIN    R20                 [get_ports {flash_data[2]}]
set_property PACKAGE_PIN    R21                 [get_ports {flash_data[3]}]
#
# Common GT reference clock
set_property PACKAGE_PIN    R8                  [get_ports {clk_gt_156p25mhz_p}]
set_property PACKAGE_PIN    R7                  [get_ports {clk_gt_156p25mhz_n}]
#
# Upsteam ports GT RX
set_property PACKAGE_PIN    AA4                 [get_ports {up0_rx_p[0]}]
set_property PACKAGE_PIN    AA3                 [get_ports {up0_rx_n[0]}]
set_property PACKAGE_PIN    Y6                  [get_ports {up0_rx_p[1]}]
set_property PACKAGE_PIN    Y5                  [get_ports {up0_rx_n[1]}]
#
# Upsteam ports GT TX
set_property PACKAGE_PIN    Y2                  [get_ports {up0_tx_p[0]}]
set_property PACKAGE_PIN    Y1                  [get_ports {up0_tx_n[0]}]
set_property PACKAGE_PIN    V2                  [get_ports {up0_tx_p[1]}]
set_property PACKAGE_PIN    V1                  [get_ports {up0_tx_n[1]}]
#
# System reference clock
set_property IOSTANDARD     LVDS                [get_ports {clk_ref_?}]
set_property PACKAGE_PIN    AD18                [get_ports {clk_ref_p}]
set_property PACKAGE_PIN    AE18                [get_ports {clk_ref_n}]
#
# System synchronization
set_property IOSTANDARD     LVDS                [get_ports {sync_?}]
set_property PACKAGE_PIN    AF17                [get_ports {sync_p}]
set_property PACKAGE_PIN    AG17                [get_ports {sync_n}]
#
# DAC #0 data interface A
set_property IOSTANDARD     LVDS_25             [get_ports {dac0_data_a_*}]
set_property IOSTANDARD     LVDS_25             [get_ports {dac0_frame_a_*}]
set_property IOSTANDARD     LVDS_25             [get_ports {dac0_clock_a_*}]
set_property PACKAGE_PIN    A16                 [get_ports {dac0_data_a_p[0]}]
set_property PACKAGE_PIN    A17                 [get_ports {dac0_data_a_n[0]}]
set_property PACKAGE_PIN    B18                 [get_ports {dac0_data_a_p[1]}]
set_property PACKAGE_PIN    A18                 [get_ports {dac0_data_a_n[1]}]
set_property PACKAGE_PIN    C17                 [get_ports {dac0_data_a_p[2]}]
set_property PACKAGE_PIN    B17                 [get_ports {dac0_data_a_n[2]}]
set_property PACKAGE_PIN    D16                 [get_ports {dac0_data_a_p[3]}]
set_property PACKAGE_PIN    C16                 [get_ports {dac0_data_a_n[3]}]
set_property PACKAGE_PIN    B22                 [get_ports {dac0_data_a_p[4]}]
set_property PACKAGE_PIN    A22                 [get_ports {dac0_data_a_n[4]}]
set_property PACKAGE_PIN    A20                 [get_ports {dac0_data_a_p[5]}]
set_property PACKAGE_PIN    A21                 [get_ports {dac0_data_a_n[5]}]
set_property PACKAGE_PIN    C19                 [get_ports {dac0_data_a_p[6]}]
set_property PACKAGE_PIN    B19                 [get_ports {dac0_data_a_n[6]}]
set_property PACKAGE_PIN    D21                 [get_ports {dac0_data_a_p[7]}]
set_property PACKAGE_PIN    C21                 [get_ports {dac0_data_a_n[7]}]
set_property PACKAGE_PIN    D22                 [get_ports {dac0_data_a_p[8]}]
set_property PACKAGE_PIN    C22                 [get_ports {dac0_data_a_n[8]}]
set_property PACKAGE_PIN    G17                 [get_ports {dac0_data_a_p[9]}]
set_property PACKAGE_PIN    F17                 [get_ports {dac0_data_a_n[9]}]
set_property PACKAGE_PIN    G18                 [get_ports {dac0_data_a_p[10]}]
set_property PACKAGE_PIN    F18                 [get_ports {dac0_data_a_n[10]}]
set_property PACKAGE_PIN    J17                 [get_ports {dac0_data_a_p[11]}]
set_property PACKAGE_PIN    H17                 [get_ports {dac0_data_a_n[11]}]
set_property PACKAGE_PIN    H20                 [get_ports {dac0_data_a_p[12]}]
set_property PACKAGE_PIN    G20                 [get_ports {dac0_data_a_n[12]}]
set_property PACKAGE_PIN    G22                 [get_ports {dac0_data_a_p[13]}]
set_property PACKAGE_PIN    F22                 [get_ports {dac0_data_a_n[13]}]
set_property PACKAGE_PIN    H21                 [get_ports {dac0_data_a_p[14]}]
set_property PACKAGE_PIN    H22                 [get_ports {dac0_data_a_n[14]}]
set_property PACKAGE_PIN    G28                 [get_ports {dac0_data_a_p[15]}]
set_property PACKAGE_PIN    F28                 [get_ports {dac0_data_a_n[15]}]
set_property PACKAGE_PIN    K18                 [get_ports {dac0_frame_a_p}]
set_property PACKAGE_PIN    J18                 [get_ports {dac0_frame_a_n}]
set_property PACKAGE_PIN    L17                 [get_ports {dac0_clock_a_p}]
set_property PACKAGE_PIN    L18                 [get_ports {dac0_clock_a_n}]
#
# DAC #0 data interface B
set_property IOSTANDARD     LVDS_25             [get_ports {dac0_data_b_*}]
set_property IOSTANDARD     LVDS_25             [get_ports {dac0_frame_b_*}]
set_property IOSTANDARD     LVDS_25             [get_ports {dac0_clock_b_*}]
set_property PACKAGE_PIN    B23                 [get_ports {dac0_data_b_p[0]}]
set_property PACKAGE_PIN    A23                 [get_ports {dac0_data_b_n[0]}]
set_property PACKAGE_PIN    C24                 [get_ports {dac0_data_b_p[1]}]
set_property PACKAGE_PIN    B24                 [get_ports {dac0_data_b_n[1]}]
set_property PACKAGE_PIN    A25                 [get_ports {dac0_data_b_p[2]}]
set_property PACKAGE_PIN    A26                 [get_ports {dac0_data_b_n[2]}]
set_property PACKAGE_PIN    B27                 [get_ports {dac0_data_b_p[3]}]
set_property PACKAGE_PIN    A27                 [get_ports {dac0_data_b_n[3]}]
set_property PACKAGE_PIN    B28                 [get_ports {dac0_data_b_p[4]}]
set_property PACKAGE_PIN    A28                 [get_ports {dac0_data_b_n[4]}]
set_property PACKAGE_PIN    B30                 [get_ports {dac0_data_b_p[5]}]
set_property PACKAGE_PIN    A30                 [get_ports {dac0_data_b_n[5]}]
set_property PACKAGE_PIN    C29                 [get_ports {dac0_data_b_p[6]}]
set_property PACKAGE_PIN    B29                 [get_ports {dac0_data_b_n[6]}]
set_property PACKAGE_PIN    D29                 [get_ports {dac0_data_b_p[7]}]
set_property PACKAGE_PIN    C30                 [get_ports {dac0_data_b_n[7]}]
set_property PACKAGE_PIN    E29                 [get_ports {dac0_data_b_p[8]}]
set_property PACKAGE_PIN    E30                 [get_ports {dac0_data_b_n[8]}]
set_property PACKAGE_PIN    E23                 [get_ports {dac0_data_b_p[9]}]
set_property PACKAGE_PIN    D23                 [get_ports {dac0_data_b_n[9]}]
set_property PACKAGE_PIN    E24                 [get_ports {dac0_data_b_p[10]}]
set_property PACKAGE_PIN    D24                 [get_ports {dac0_data_b_n[10]}]
set_property PACKAGE_PIN    F25                 [get_ports {dac0_data_b_p[11]}]
set_property PACKAGE_PIN    E25                 [get_ports {dac0_data_b_n[11]}]
set_property PACKAGE_PIN    F26                 [get_ports {dac0_data_b_p[12]}]
set_property PACKAGE_PIN    E26                 [get_ports {dac0_data_b_n[12]}]
set_property PACKAGE_PIN    J19                 [get_ports {dac0_data_b_p[13]}]
set_property PACKAGE_PIN    H19                 [get_ports {dac0_data_b_n[13]}]
set_property PACKAGE_PIN    G27                 [get_ports {dac0_data_b_p[14]}]
set_property PACKAGE_PIN    F27                 [get_ports {dac0_data_b_n[14]}]
set_property PACKAGE_PIN    G29                 [get_ports {dac0_data_b_p[15]}]
set_property PACKAGE_PIN    F30                 [get_ports {dac0_data_b_n[15]}]
set_property PACKAGE_PIN    H30                 [get_ports {dac0_frame_b_p}]
set_property PACKAGE_PIN    G30                 [get_ports {dac0_frame_b_n}]
set_property PACKAGE_PIN    H26                 [get_ports {dac0_clock_b_p}]
set_property PACKAGE_PIN    H27                 [get_ports {dac0_clock_b_n}]
#
# DAC #0 control interface
set_property IOSTANDARD     LVCMOS33            [get_ports {dac0_spi_*}]
set_property PACKAGE_PIN    V30                 [get_ports {dac0_spi_rstn}]
set_property PACKAGE_PIN    V29                 [get_ports {dac0_spi_cs_n}]
set_property PACKAGE_PIN    U30                 [get_ports {dac0_spi_sclk}]
set_property PACKAGE_PIN    U29                 [get_ports {dac0_spi_mosi}]
set_property PACKAGE_PIN    T30                 [get_ports {dac0_spi_miso}]
#
# DAC #1 data interface A
set_property IOSTANDARD     LVDS_25             [get_ports {dac1_data_a_*}]
set_property IOSTANDARD     LVDS_25             [get_ports {dac1_frame_a_*}]
set_property IOSTANDARD     LVDS_25             [get_ports {dac1_clock_a_*}]
set_property PACKAGE_PIN    Y26                 [get_ports {dac1_data_a_p[0]}]
set_property PACKAGE_PIN    AA26                [get_ports {dac1_data_a_n[0]}]
set_property PACKAGE_PIN    AA22                [get_ports {dac1_data_a_p[1]}]
set_property PACKAGE_PIN    AA23                [get_ports {dac1_data_a_n[1]}]
set_property PACKAGE_PIN    Y30                 [get_ports {dac1_data_a_p[2]}]
set_property PACKAGE_PIN    AA30                [get_ports {dac1_data_a_n[2]}]
set_property PACKAGE_PIN    AC20                [get_ports {dac1_data_a_p[3]}]
set_property PACKAGE_PIN    AC21                [get_ports {dac1_data_a_n[3]}]
set_property PACKAGE_PIN    AB22                [get_ports {dac1_data_a_p[4]}]
set_property PACKAGE_PIN    AB23                [get_ports {dac1_data_a_n[4]}]
set_property PACKAGE_PIN    AC24                [get_ports {dac1_data_a_p[5]}]
set_property PACKAGE_PIN    AD24                [get_ports {dac1_data_a_n[5]}]
set_property PACKAGE_PIN    AB24                [get_ports {dac1_data_a_p[6]}]
set_property PACKAGE_PIN    AC25                [get_ports {dac1_data_a_n[6]}]
set_property PACKAGE_PIN    AD21                [get_ports {dac1_data_a_p[7]}]
set_property PACKAGE_PIN    AE21                [get_ports {dac1_data_a_n[7]}]
set_property PACKAGE_PIN    AC22                [get_ports {dac1_data_a_p[8]}]
set_property PACKAGE_PIN    AD22                [get_ports {dac1_data_a_n[8]}]
set_property PACKAGE_PIN    AG22                [get_ports {dac1_data_a_p[9]}]
set_property PACKAGE_PIN    AH22                [get_ports {dac1_data_a_n[9]}]
set_property PACKAGE_PIN    AE25                [get_ports {dac1_data_a_p[10]}]
set_property PACKAGE_PIN    AF25                [get_ports {dac1_data_a_n[10]}]
set_property PACKAGE_PIN    AG25                [get_ports {dac1_data_a_p[11]}]
set_property PACKAGE_PIN    AH25                [get_ports {dac1_data_a_n[11]}]
set_property PACKAGE_PIN    AJ22                [get_ports {dac1_data_a_p[12]}]
set_property PACKAGE_PIN    AJ23                [get_ports {dac1_data_a_n[12]}]
set_property PACKAGE_PIN    AH21                [get_ports {dac1_data_a_p[13]}]
set_property PACKAGE_PIN    AJ21                [get_ports {dac1_data_a_n[13]}]
set_property PACKAGE_PIN    AJ24                [get_ports {dac1_data_a_p[14]}]
set_property PACKAGE_PIN    AK25                [get_ports {dac1_data_a_n[14]}]
set_property PACKAGE_PIN    AK23                [get_ports {dac1_data_a_p[15]}]
set_property PACKAGE_PIN    AK24                [get_ports {dac1_data_a_n[15]}]
set_property PACKAGE_PIN    AK20                [get_ports {dac1_frame_a_p}]
set_property PACKAGE_PIN    AK21                [get_ports {dac1_frame_a_n}]
set_property PACKAGE_PIN    AF20                [get_ports {dac1_clock_a_p}]
set_property PACKAGE_PIN    AF21                [get_ports {dac1_clock_a_n}]
#
# DAC #1 data interface B
set_property IOSTANDARD     LVDS_25             [get_ports {dac1_data_b_*}]
set_property IOSTANDARD     LVDS_25             [get_ports {dac1_frame_b_*}]
set_property IOSTANDARD     LVDS_25             [get_ports {dac1_clock_b_*}]
set_property PACKAGE_PIN    Y28                 [get_ports {dac1_data_b_p[0]}]
set_property PACKAGE_PIN    AA28                [get_ports {dac1_data_b_n[0]}]
set_property PACKAGE_PIN    AJ26                [get_ports {dac1_data_b_p[1]}]
set_property PACKAGE_PIN    AK26                [get_ports {dac1_data_b_n[1]}]
set_property PACKAGE_PIN    Y21                 [get_ports {dac1_data_b_p[2]}]
set_property PACKAGE_PIN    AA21                [get_ports {dac1_data_b_n[2]}]
set_property PACKAGE_PIN    W29                 [get_ports {dac1_data_b_p[3]}]
set_property PACKAGE_PIN    Y29                 [get_ports {dac1_data_b_n[3]}]
set_property PACKAGE_PIN    AC29                [get_ports {dac1_data_b_p[4]}]
set_property PACKAGE_PIN    AC30                [get_ports {dac1_data_b_n[4]}]
set_property PACKAGE_PIN    AA27                [get_ports {dac1_data_b_p[5]}]
set_property PACKAGE_PIN    AB28                [get_ports {dac1_data_b_n[5]}]
set_property PACKAGE_PIN    AE30                [get_ports {dac1_data_b_p[6]}]
set_property PACKAGE_PIN    AF30                [get_ports {dac1_data_b_n[6]}]
set_property PACKAGE_PIN    AD29                [get_ports {dac1_data_b_p[7]}]
set_property PACKAGE_PIN    AE29                [get_ports {dac1_data_b_n[7]}]
set_property PACKAGE_PIN    AF26                [get_ports {dac1_data_b_p[8]}]
set_property PACKAGE_PIN    AF27                [get_ports {dac1_data_b_n[8]}]
set_property PACKAGE_PIN    AG27                [get_ports {dac1_data_b_p[9]}]
set_property PACKAGE_PIN    AG28                [get_ports {dac1_data_b_n[9]}]
set_property PACKAGE_PIN    AH26                [get_ports {dac1_data_b_p[10]}]
set_property PACKAGE_PIN    AH27                [get_ports {dac1_data_b_n[10]}]
set_property PACKAGE_PIN    AG20                [get_ports {dac1_data_b_p[11]}]
set_property PACKAGE_PIN    AH20                [get_ports {dac1_data_b_n[11]}]
set_property PACKAGE_PIN    AG30                [get_ports {dac1_data_b_p[12]}]
set_property PACKAGE_PIN    AH30                [get_ports {dac1_data_b_n[12]}]
set_property PACKAGE_PIN    AJ28                [get_ports {dac1_data_b_p[13]}]
set_property PACKAGE_PIN    AJ29                [get_ports {dac1_data_b_n[13]}]
set_property PACKAGE_PIN    AJ27                [get_ports {dac1_data_b_p[14]}]
set_property PACKAGE_PIN    AK28                [get_ports {dac1_data_b_n[14]}]
set_property PACKAGE_PIN    AK29                [get_ports {dac1_data_b_p[15]}]
set_property PACKAGE_PIN    AK30                [get_ports {dac1_data_b_n[15]}]
set_property PACKAGE_PIN    W27                 [get_ports {dac1_frame_b_p}]
set_property PACKAGE_PIN    W28                 [get_ports {dac1_frame_b_n}]
set_property PACKAGE_PIN    Y23                 [get_ports {dac1_clock_b_p}]
set_property PACKAGE_PIN    Y24                 [get_ports {dac1_clock_b_n}]
#
# DAC #1 control interface
set_property IOSTANDARD     LVCMOS33            [get_ports {dac1_spi_*}]
set_property PACKAGE_PIN    V27                 [get_ports {dac1_spi_rstn}]
set_property PACKAGE_PIN    W26                 [get_ports {dac1_spi_cs_n}]
set_property PACKAGE_PIN    V26                 [get_ports {dac1_spi_sclk}]
set_property PACKAGE_PIN    V25                 [get_ports {dac1_spi_mosi}]
set_property PACKAGE_PIN    W24                 [get_ports {dac1_spi_miso}]
#
# JESD204B GT reference clock
set_property PACKAGE_PIN    J8                  [get_ports {clk_jesd204b_gt_p}]
set_property PACKAGE_PIN    J7                  [get_ports {clk_jesd204b_gt_n}]
#
# JESD204B SYSREF
set_property IOSTANDARD     LVDS                [get_ports {sysref_jesd204b_*}]
set_property PACKAGE_PIN    AD17                [get_ports {sysref_jesd204b_p}]
set_property PACKAGE_PIN    AD16                [get_ports {sysref_jesd204b_n}]
#
# JESD204B SYNCB outputs
set_property IOSTANDARD     LVDS                [get_ports {adc?_jesd204b_syncb_?}]
set_property PACKAGE_PIN    AK16                [get_ports {adc0_jesd204b_syncb_p}]
set_property PACKAGE_PIN    AK15                [get_ports {adc0_jesd204b_syncb_n}]
set_property PACKAGE_PIN    AH16                [get_ports {adc1_jesd204b_syncb_p}]
set_property PACKAGE_PIN    AJ16                [get_ports {adc1_jesd204b_syncb_n}]
set_property PACKAGE_PIN    AH17                [get_ports {adc2_jesd204b_syncb_p}]
set_property PACKAGE_PIN    AJ17                [get_ports {adc2_jesd204b_syncb_n}]
set_property PACKAGE_PIN    AJ18                [get_ports {adc3_jesd204b_syncb_p}]
set_property PACKAGE_PIN    AK18                [get_ports {adc3_jesd204b_syncb_n}]
#
# JESD204B ADC #0 GT RX
set_property PACKAGE_PIN    K6                  [get_ports {adc0_jesd204b_gt_rx_p[0]}]
set_property PACKAGE_PIN    K5                  [get_ports {adc0_jesd204b_gt_rx_n[0]}]
set_property PACKAGE_PIN    H6                  [get_ports {adc0_jesd204b_gt_rx_p[1]}]
set_property PACKAGE_PIN    H5                  [get_ports {adc0_jesd204b_gt_rx_n[1]}]
#
# JESD204B ADC #1 GT RX
set_property PACKAGE_PIN    G4                  [get_ports {adc1_jesd204b_gt_rx_p[0]}]
set_property PACKAGE_PIN    G3                  [get_ports {adc1_jesd204b_gt_rx_n[0]}]
set_property PACKAGE_PIN    F6                  [get_ports {adc1_jesd204b_gt_rx_p[1]}]
set_property PACKAGE_PIN    F5                  [get_ports {adc1_jesd204b_gt_rx_n[1]}]
#
# JESD204B ADC #2 GT RX
set_property PACKAGE_PIN    E4                  [get_ports {adc2_jesd204b_gt_rx_p[0]}]
set_property PACKAGE_PIN    E3                  [get_ports {adc2_jesd204b_gt_rx_n[0]}]
set_property PACKAGE_PIN    D6                  [get_ports {adc2_jesd204b_gt_rx_p[1]}]
set_property PACKAGE_PIN    D5                  [get_ports {adc2_jesd204b_gt_rx_n[1]}]
#
# JESD204B ADC #3 GT RX
set_property PACKAGE_PIN    B6                  [get_ports {adc3_jesd204b_gt_rx_p[0]}]
set_property PACKAGE_PIN    B5                  [get_ports {adc3_jesd204b_gt_rx_n[0]}]
set_property PACKAGE_PIN    A8                  [get_ports {adc3_jesd204b_gt_rx_p[1]}]
set_property PACKAGE_PIN    A7                  [get_ports {adc3_jesd204b_gt_rx_n[1]}]
#
# ADC #0 control
set_property IOSTANDARD     LVCMOS18            [get_ports {adc0_pdwn_*}]
set_property IOSTANDARD     LVCMOS18            [get_ports {adc0_gpio_*}]
set_property IOSTANDARD     LVCMOS18            [get_ports {adc0_spi*}]
set_property PACKAGE_PIN    H16                 [get_ports {adc0_pdwn_stby}]
set_property PACKAGE_PIN    F16                 [get_ports {adc0_gpio_a0}]
set_property PACKAGE_PIN    E16                 [get_ports {adc0_gpio_b0}]
set_property PACKAGE_PIN    D11                 [get_ports {adc0_spi_cs_n}]
set_property PACKAGE_PIN    C11                 [get_ports {adc0_spi_sclk}]
set_property PACKAGE_PIN    A11                 [get_ports {adc0_spi_sdio}]
#
# ADC #1 control
set_property IOSTANDARD     LVCMOS18            [get_ports {adc1_pdwn_*}]
set_property IOSTANDARD     LVCMOS18            [get_ports {adc1_gpio_*}]
set_property IOSTANDARD     LVCMOS18            [get_ports {adc1_spi*}]
set_property PACKAGE_PIN    G12                 [get_ports {adc1_pdwn_stby}]
set_property PACKAGE_PIN    H11                 [get_ports {adc1_gpio_a0}]
set_property PACKAGE_PIN    H12                 [get_ports {adc1_gpio_b0}]
set_property PACKAGE_PIN    C12                 [get_ports {adc1_spi_cs_n}]
set_property PACKAGE_PIN    B12                 [get_ports {adc1_spi_sclk}]
set_property PACKAGE_PIN    A13                 [get_ports {adc1_spi_sdio}]
#
# ADC #2 control
set_property IOSTANDARD     LVCMOS18            [get_ports {adc2_pdwn_*}]
set_property IOSTANDARD     LVCMOS18            [get_ports {adc2_gpio_*}]
set_property IOSTANDARD     LVCMOS18            [get_ports {adc2_spi*}]
set_property PACKAGE_PIN    B13                 [get_ports {adc2_pdwn_stby}]
set_property PACKAGE_PIN    B14                 [get_ports {adc2_gpio_a0}]
set_property PACKAGE_PIN    J13                 [get_ports {adc2_gpio_b0}]
set_property PACKAGE_PIN    C14                 [get_ports {adc2_spi_cs_n}]
set_property PACKAGE_PIN    D14                 [get_ports {adc2_spi_sclk}]
set_property PACKAGE_PIN    E14                 [get_ports {adc2_spi_sdio}]
#
# ADC #3 control
set_property IOSTANDARD     LVCMOS18            [get_ports {adc3_pdwn_*}]
set_property IOSTANDARD     LVCMOS18            [get_ports {adc3_gpio_*}]
set_property IOSTANDARD     LVCMOS18            [get_ports {adc3_spi*}]
set_property PACKAGE_PIN    C15                 [get_ports {adc3_pdwn_stby}]
set_property PACKAGE_PIN    A15                 [get_ports {adc3_gpio_a0}]
set_property PACKAGE_PIN    B15                 [get_ports {adc3_gpio_b0}]
set_property PACKAGE_PIN    E15                 [get_ports {adc3_spi_cs_n}]
set_property PACKAGE_PIN    F15                 [get_ports {adc3_spi_sclk}]
set_property PACKAGE_PIN    G15                 [get_ports {adc3_spi_sdio}]
#
# LMK0482 output clock/synchronization
set_property IOSTANDARD     LVDS                [get_ports {lmk0482_clkin0_?}]
set_property PACKAGE_PIN    AJ19                [get_ports {lmk0482_clkin0_p}]
set_property PACKAGE_PIN    AK19                [get_ports {lmk0482_clkin0_n}]
#
# LMK0482 control
set_property IOSTANDARD     LVCMOS33            [get_ports {lmk0482_reset}]
set_property IOSTANDARD     LVCMOS33            [get_ports {lmk0482_sync}]
set_property IOSTANDARD     LVCMOS33            [get_ports {lmk0482_clkin_sel?}]
set_property IOSTANDARD     LVCMOS33            [get_ports {lmk0482_status_ld?}]
set_property IOSTANDARD     LVCMOS33            [get_ports {lmk0482_spi_*}]
set_property PACKAGE_PIN    V24                 [get_ports {lmk0482_reset}]
set_property PACKAGE_PIN    W23                 [get_ports {lmk0482_sync}]
set_property PACKAGE_PIN    W22                 [get_ports {lmk0482_clkin_sel0}]
set_property PACKAGE_PIN    W21                 [get_ports {lmk0482_clkin_sel1}]
set_property PACKAGE_PIN    W19                 [get_ports {lmk0482_status_ld1}]
set_property PACKAGE_PIN    V22                 [get_ports {lmk0482_status_ld2}]
set_property PACKAGE_PIN    V21                 [get_ports {lmk0482_spi_cs_n}]
set_property PACKAGE_PIN    V19                 [get_ports {lmk0482_spi_sclk}]
set_property PACKAGE_PIN    U22                 [get_ports {lmk0482_spi_sdio}]
#
# MKBUS
set_property IOSTANDARD     LVCMOS25            [get_ports {mkbus_*}]
set_property PACKAGE_PIN    K28                 [get_ports {mkbus_clk}]
set_property PACKAGE_PIN    M27                 [get_ports {mkbus_nrst}]
set_property PACKAGE_PIN    N27                 [get_ports {mkbus_ready}]
set_property PACKAGE_PIN    N26                 [get_ports {mkbus_valid}]
set_property PACKAGE_PIN    J26                 [get_ports {mkbus_code[0]}]
set_property PACKAGE_PIN    J27                 [get_ports {mkbus_code[1]}]
set_property PACKAGE_PIN    N29                 [get_ports {mkbus_dt[0]}]
set_property PACKAGE_PIN    M29                 [get_ports {mkbus_dt[1]}]
set_property PACKAGE_PIN    N30                 [get_ports {mkbus_dt[2]}]
set_property PACKAGE_PIN    M30                 [get_ports {mkbus_dt[3]}]
set_property PACKAGE_PIN    L30                 [get_ports {mkbus_dt[4]}]
set_property PACKAGE_PIN    K30                 [get_ports {mkbus_dt[5]}]
set_property PACKAGE_PIN    J29                 [get_ports {mkbus_dt[6]}]
set_property PACKAGE_PIN    J28                 [get_ports {mkbus_dt[7]}]