# System clock
set_property IOSTANDARD     DIFF_SSTL15         [get_ports {clk_100mhz_?}]
set_property PACKAGE_PIN    D27                 [get_ports {clk_100mhz_p}]
set_property PACKAGE_PIN    C27                 [get_ports {clk_100mhz_n}]
#
# DDR3 Reset
set_property SLEW           FAST                [get_ports {ddr3_reset_n}]
set_property IOSTANDARD     LVCMOS15            [get_ports {ddr3_reset_n}]
set_property PACKAGE_PIN    C17                 [get_ports {ddr3_reset_n}]
#
# DDR3 Clock
set_property SLEW           FAST                [get_ports {ddr3_ck_?[0]}]
set_property IOSTANDARD     DIFF_SSTL15         [get_ports {ddr3_ck_?[0]}]
set_property PACKAGE_PIN    J17                 [get_ports {ddr3_ck_p[0]}]
set_property PACKAGE_PIN    H17                 [get_ports {ddr3_ck_n[0]}]
#
# DDR3 Control
set_property SLEW           FAST                [get_ports {ddr3_addr[*]}]
set_property IOSTANDARD     SSTL15              [get_ports {ddr3_addr[*]}]
set_property PACKAGE_PIN    G22                 [get_ports {ddr3_addr[0]}]
set_property PACKAGE_PIN    C21                 [get_ports {ddr3_addr[1]}]
set_property PACKAGE_PIN    D21                 [get_ports {ddr3_addr[2]}]
set_property PACKAGE_PIN    H22                 [get_ports {ddr3_addr[3]}]
set_property PACKAGE_PIN    H21                 [get_ports {ddr3_addr[4]}]
set_property PACKAGE_PIN    K19                 [get_ports {ddr3_addr[5]}]
set_property PACKAGE_PIN    L18                 [get_ports {ddr3_addr[6]}]
set_property PACKAGE_PIN    L17                 [get_ports {ddr3_addr[7]}]
set_property PACKAGE_PIN    H19                 [get_ports {ddr3_addr[8]}]
set_property PACKAGE_PIN    J19                 [get_ports {ddr3_addr[9]}]
set_property PACKAGE_PIN    G20                 [get_ports {ddr3_addr[10]}]
set_property PACKAGE_PIN    H20                 [get_ports {ddr3_addr[11]}]
set_property PACKAGE_PIN    J18                 [get_ports {ddr3_addr[12]}]
set_property PACKAGE_PIN    K18                 [get_ports {ddr3_addr[13]}]
#
set_property SLEW           FAST                [get_ports {ddr3_ba[*]}]
set_property IOSTANDARD     SSTL15              [get_ports {ddr3_ba[*]}]
set_property PACKAGE_PIN    C22                 [get_ports {ddr3_ba[0]}]
set_property PACKAGE_PIN    D22                 [get_ports {ddr3_ba[1]}]
set_property PACKAGE_PIN    F22                 [get_ports {ddr3_ba[2]}]
#
set_property SLEW           FAST                [get_ports {ddr3_cas_n}]
set_property IOSTANDARD     SSTL15              [get_ports {ddr3_cas_n}]
set_property PACKAGE_PIN    E21                 [get_ports {ddr3_cas_n}]
#
set_property SLEW           FAST                [get_ports {ddr3_cke[0]}]
set_property IOSTANDARD     SSTL15              [get_ports {ddr3_cke[0]}]
set_property PACKAGE_PIN    D16                 [get_ports {ddr3_cke[0]}]
#
set_property SLEW           FAST                [get_ports {ddr3_cs_n[0]}]
set_property IOSTANDARD     SSTL15              [get_ports {ddr3_cs_n[0]}]
set_property PACKAGE_PIN    E20                 [get_ports {ddr3_cs_n[0]}]
#
set_property SLEW           FAST                [get_ports {ddr3_odt[0]}]
set_property IOSTANDARD     SSTL15              [get_ports {ddr3_odt[0]}]
set_property PACKAGE_PIN    C16                 [get_ports {ddr3_odt[0]}]
#
set_property SLEW           FAST                [get_ports {ddr3_ras_n}]
set_property IOSTANDARD     SSTL15              [get_ports {ddr3_ras_n}]
set_property PACKAGE_PIN    F21                 [get_ports {ddr3_ras_n}]
#
set_property SLEW           FAST                [get_ports {ddr3_we_n}]
set_property IOSTANDARD     SSTL15              [get_ports {ddr3_we_n}]
set_property PACKAGE_PIN    F20                 [get_ports {ddr3_we_n}]
#
# DDR3 DQ
set_property SLEW           FAST                [get_ports {ddr3_dq[*]}]
set_property IOSTANDARD     SSTL15              [get_ports {ddr3_dq[*]}]
set_property PACKAGE_PIN    A16                 [get_ports {ddr3_dq[0]}]
set_property PACKAGE_PIN    A17                 [get_ports {ddr3_dq[1]}]
set_property PACKAGE_PIN    B18                 [get_ports {ddr3_dq[2]}]
set_property PACKAGE_PIN    A18                 [get_ports {ddr3_dq[3]}]
set_property PACKAGE_PIN    B22                 [get_ports {ddr3_dq[4]}]
set_property PACKAGE_PIN    A22                 [get_ports {ddr3_dq[5]}]
set_property PACKAGE_PIN    C19                 [get_ports {ddr3_dq[6]}]
set_property PACKAGE_PIN    B19                 [get_ports {ddr3_dq[7]}]
set_property PACKAGE_PIN    A23                 [get_ports {ddr3_dq[8]}]
set_property PACKAGE_PIN    E23                 [get_ports {ddr3_dq[9]}]
set_property PACKAGE_PIN    D23                 [get_ports {ddr3_dq[10]}]
set_property PACKAGE_PIN    E24                 [get_ports {ddr3_dq[11]}]
set_property PACKAGE_PIN    D24                 [get_ports {ddr3_dq[12]}]
set_property PACKAGE_PIN    F26                 [get_ports {ddr3_dq[13]}]
set_property PACKAGE_PIN    E26                 [get_ports {ddr3_dq[14]}]
set_property PACKAGE_PIN    G23                 [get_ports {ddr3_dq[15]}]
#
# DDR3 DQS
set_property SLEW           FAST                [get_ports {ddr3_dqs_?[*]}]
set_property IOSTANDARD     DIFF_SSTL15         [get_ports {ddr3_dqs_?[*]}]
set_property PACKAGE_PIN    A20                 [get_ports {ddr3_dqs_p[0]}]
set_property PACKAGE_PIN    A21                 [get_ports {ddr3_dqs_n[0]}]
set_property PACKAGE_PIN    F25                 [get_ports {ddr3_dqs_p[1]}]
set_property PACKAGE_PIN    E25                 [get_ports {ddr3_dqs_n[1]}]
#
# DDR3 DM
set_property SLEW           FAST                [get_ports {ddr3_dm[*]}]
set_property IOSTANDARD     SSTL15              [get_ports {ddr3_dm[*]}]
set_property PACKAGE_PIN    C20                 [get_ports {ddr3_dm[0]}]
set_property PACKAGE_PIN    B23                 [get_ports {ddr3_dm[1]}]
#
# QSPI Flash
set_property IOSTANDARD     LVCMOS33            [get_ports {flash_*}]
set_property PACKAGE_PIN    U19                 [get_ports {flash_cs_n}]
set_property PACKAGE_PIN    P24                 [get_ports {flash_data[0]}]
set_property PACKAGE_PIN    R25                 [get_ports {flash_data[1]}]
set_property PACKAGE_PIN    R20                 [get_ports {flash_data[2]}]
set_property PACKAGE_PIN    R21                 [get_ports {flash_data[3]}]
#
# Common GT reference clock
set_property PACKAGE_PIN    R8                  [get_ports {clk_gt_p}]
set_property PACKAGE_PIN    R7                  [get_ports {clk_gt_n}]
#
# Upsteam ports GT RX
set_property PACKAGE_PIN    AA4                 [get_ports {up0_rx_p[0]}]
set_property PACKAGE_PIN    AA3                 [get_ports {up0_rx_n[0]}]
set_property PACKAGE_PIN    Y6                  [get_ports {up0_rx_p[1]}]
set_property PACKAGE_PIN    Y5                  [get_ports {up0_rx_n[1]}]
#
# Upsteam ports GT TX
set_property PACKAGE_PIN    Y2                  [get_ports {up0_tx_p[0]}]
set_property PACKAGE_PIN    Y1                  [get_ports {up0_tx_n[0]}]
set_property PACKAGE_PIN    V2                  [get_ports {up0_tx_p[1]}]
set_property PACKAGE_PIN    V1                  [get_ports {up0_tx_n[1]}]
#
# ADC/DAC reference clock
set_property IOSTANDARD     LVDS                [get_ports {clk_ref_?}]
set_property PACKAGE_PIN    AH4                 [get_ports {clk_ref_p}]
set_property PACKAGE_PIN    AJ4                 [get_ports {clk_ref_n}]
#
# DAC data interface A
set_property IOSTANDARD     LVDS                [get_ports {dac_data_a_*}]
set_property IOSTANDARD     LVDS                [get_ports {dac_frame_a_*}]
set_property IOSTANDARD     LVDS                [get_ports {dac_clock_a_*}]
set_property PACKAGE_PIN    AC2                 [get_ports {dac_data_a_p[0]}]
set_property PACKAGE_PIN    AC1                 [get_ports {dac_data_a_n[0]}]
set_property PACKAGE_PIN    AD2                 [get_ports {dac_data_a_p[1]}]
set_property PACKAGE_PIN    AD1                 [get_ports {dac_data_a_n[1]}]
set_property PACKAGE_PIN    AD4                 [get_ports {dac_data_a_p[2]}]
set_property PACKAGE_PIN    AD3                 [get_ports {dac_data_a_n[2]}]
set_property PACKAGE_PIN    AE1                 [get_ports {dac_data_a_p[3]}]
set_property PACKAGE_PIN    AF1                 [get_ports {dac_data_a_n[3]}]
set_property PACKAGE_PIN    AF3                 [get_ports {dac_data_a_p[4]}]
set_property PACKAGE_PIN    AF2                 [get_ports {dac_data_a_n[4]}]
set_property PACKAGE_PIN    AE4                 [get_ports {dac_data_a_p[5]}]
set_property PACKAGE_PIN    AE3                 [get_ports {dac_data_a_n[5]}]
set_property PACKAGE_PIN    AG2                 [get_ports {dac_data_a_p[6]}]
set_property PACKAGE_PIN    AH1                 [get_ports {dac_data_a_n[6]}]
set_property PACKAGE_PIN    AG4                 [get_ports {dac_data_a_p[7]}]
set_property PACKAGE_PIN    AG3                 [get_ports {dac_data_a_n[7]}]
set_property PACKAGE_PIN    AH2                 [get_ports {dac_data_a_p[8]}]
set_property PACKAGE_PIN    AJ2                 [get_ports {dac_data_a_n[8]}]
set_property PACKAGE_PIN    AJ1                 [get_ports {dac_data_a_p[9]}]
set_property PACKAGE_PIN    AK1                 [get_ports {dac_data_a_n[9]}]
set_property PACKAGE_PIN    AJ3                 [get_ports {dac_data_a_p[10]}]
set_property PACKAGE_PIN    AK3                 [get_ports {dac_data_a_n[10]}]
set_property PACKAGE_PIN    AK5                 [get_ports {dac_data_a_p[11]}]
set_property PACKAGE_PIN    AK4                 [get_ports {dac_data_a_n[11]}]
set_property PACKAGE_PIN    AJ6                 [get_ports {dac_data_a_p[12]}]
set_property PACKAGE_PIN    AK6                 [get_ports {dac_data_a_n[12]}]
set_property PACKAGE_PIN    AJ8                 [get_ports {dac_data_a_p[13]}]
set_property PACKAGE_PIN    AK8                 [get_ports {dac_data_a_n[13]}]
set_property PACKAGE_PIN    AH7                 [get_ports {dac_data_a_p[14]}]
set_property PACKAGE_PIN    AJ7                 [get_ports {dac_data_a_n[14]}]
set_property PACKAGE_PIN    AF7                 [get_ports {dac_data_a_p[15]}]
set_property PACKAGE_PIN    AG7                 [get_ports {dac_data_a_n[15]}]
set_property PACKAGE_PIN    AC5                 [get_ports {dac_frame_a_p}]
set_property PACKAGE_PIN    AC4                 [get_ports {dac_frame_a_n}]
set_property PACKAGE_PIN    AD6                 [get_ports {dac_clock_a_p}]
set_property PACKAGE_PIN    AE6                 [get_ports {dac_clock_a_n}]
#
# DAC data interface B
set_property IOSTANDARD     LVDS                [get_ports {dac_data_b_*}]
set_property IOSTANDARD     LVDS                [get_ports {dac_frame_b_*}]
set_property IOSTANDARD     LVDS                [get_ports {dac_clock_b_*}]
set_property PACKAGE_PIN    AJ9                 [get_ports {dac_data_b_p[0]}]
set_property PACKAGE_PIN    AK9                 [get_ports {dac_data_b_n[0]}]
set_property PACKAGE_PIN    AG9                 [get_ports {dac_data_b_p[1]}]
set_property PACKAGE_PIN    AH9                 [get_ports {dac_data_b_n[1]}]
set_property PACKAGE_PIN    AK11                [get_ports {dac_data_b_p[2]}]
set_property PACKAGE_PIN    AK10                [get_ports {dac_data_b_n[2]}]
set_property PACKAGE_PIN    AH11                [get_ports {dac_data_b_p[3]}]
set_property PACKAGE_PIN    AJ11                [get_ports {dac_data_b_n[3]}]
set_property PACKAGE_PIN    AD8                 [get_ports {dac_data_b_p[4]}]
set_property PACKAGE_PIN    AE8                 [get_ports {dac_data_b_n[4]}]
set_property PACKAGE_PIN    AJ13                [get_ports {dac_data_b_p[5]}]
set_property PACKAGE_PIN    AJ12                [get_ports {dac_data_b_n[5]}]
set_property PACKAGE_PIN    AG13                [get_ports {dac_data_b_p[6]}]
set_property PACKAGE_PIN    AH12                [get_ports {dac_data_b_n[6]}]
set_property PACKAGE_PIN    AK14                [get_ports {dac_data_b_p[7]}]
set_property PACKAGE_PIN    AK13                [get_ports {dac_data_b_n[7]}]
set_property PACKAGE_PIN    AH14                [get_ports {dac_data_b_p[8]}]
set_property PACKAGE_PIN    AJ14                [get_ports {dac_data_b_n[8]}]
set_property PACKAGE_PIN    AF12                [get_ports {dac_data_b_p[9]}]
set_property PACKAGE_PIN    AG12                [get_ports {dac_data_b_n[9]}]
set_property PACKAGE_PIN    AD9                 [get_ports {dac_data_b_p[10]}]
set_property PACKAGE_PIN    AE9                 [get_ports {dac_data_b_n[10]}]
set_property PACKAGE_PIN    AB9                 [get_ports {dac_data_b_p[11]}]
set_property PACKAGE_PIN    AC9                 [get_ports {dac_data_b_n[11]}]
set_property PACKAGE_PIN    AA8                 [get_ports {dac_data_b_p[12]}]
set_property PACKAGE_PIN    AB8                 [get_ports {dac_data_b_n[12]}]
set_property PACKAGE_PIN    AB10                [get_ports {dac_data_b_p[13]}]
set_property PACKAGE_PIN    AC10                [get_ports {dac_data_b_n[13]}]
set_property PACKAGE_PIN    AA11                [get_ports {dac_data_b_p[14]}]
set_property PACKAGE_PIN    AA10                [get_ports {dac_data_b_n[14]}]
set_property PACKAGE_PIN    Y11                 [get_ports {dac_data_b_p[15]}]
set_property PACKAGE_PIN    Y10                 [get_ports {dac_data_b_n[15]}]
set_property PACKAGE_PIN    AA12                [get_ports {dac_frame_b_p}]
set_property PACKAGE_PIN    AB12                [get_ports {dac_frame_b_n}]
set_property PACKAGE_PIN    AC12                [get_ports {dac_clock_b_p}]
set_property PACKAGE_PIN    AC11                [get_ports {dac_clock_b_n}]
#
# DAC control interface
set_property IOSTANDARD     LVCMOS33            [get_ports {dac_spi_*}]
set_property PACKAGE_PIN    Y26                 [get_ports {dac_spi_rstn}]
set_property PACKAGE_PIN    W27                 [get_ports {dac_spi_cs_n}]
set_property PACKAGE_PIN    Y25                 [get_ports {dac_spi_sclk}]
set_property PACKAGE_PIN    W29                 [get_ports {dac_spi_mosi}]
set_property PACKAGE_PIN    W28                 [get_ports {dac_spi_miso}]